# Generated by Django 4.2.30 on 2026-05-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_registrationcode_customer_registration_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='courses/attachments/'),
        ),
    ]
