# Generated by Django 4.2.30 on 2026-05-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Banka adı', max_length=120)),
                ('account_holder', models.CharField(default='Volkan Güler', max_length=150)),
                ('iban', models.CharField(max_length=50)),
                ('youtube_join_url', models.URLField(default='https://www.youtube.com/channel/UCki5h5npPunCWXENktDcNBA/join')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
