# Generated by Django 4.2.30 on 2026-05-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_banktransferorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentor',
            old_name='blur_photo',
            new_name='use_anonymous_photo',
        ),
        migrations.AddField(
            model_name='mentor',
            name='anonymous_photo',
            field=models.CharField(choices=[('anonymous/blur-1.jpg', 'Anonim Görsel 1'), ('anonymous/blur-2.jpg', 'Anonim Görsel 2'), ('anonymous/blur-3.jpg', 'Anonim Görsel 3'), ('anonymous/blur-4.jpg', 'Anonim Görsel 4'), ('anonymous/blur-5.jpg', 'Anonim Görsel 5'), ('anonymous/blur-6.jpg', 'Anonim Görsel 6'), ('anonymous/blur-7.jpg', 'Anonim Görsel 7'), ('anonymous/blur-8.jpg', 'Anonim Görsel 8'), ('anonymous/blur-9.jpg', 'Anonim Görsel 9'), ('anonymous/blur-10.jpg', 'Anonim Görsel 10')], default='anonymous/blur-1.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='mentor',
            name='show_on_homepage',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='skills',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
