# Generated by Django 4.2.30 on 2026-05-07 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_blur_photo_mentor_use_anonymous_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('category', models.CharField(choices=[('basari-hikayesi', 'Başarı Hikayesi'), ('kariyer', 'Kariyer'), ('topluluk', 'Topluluk'), ('duyuru', 'Duyuru')], default='basari-hikayesi', max_length=50)),
                ('excerpt', models.TextField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('author_name', models.CharField(default='Rotaya', max_length=100)),
                ('author_avatar', models.ImageField(blank=True, null=True, upload_to='blog/authors/')),
                ('read_time', models.PositiveIntegerField(default=5)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
