# Generated by Django 4.2.30 on 2026-05-07 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='author_avatar',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author_name',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to='core.mentor'),
        ),
    ]
